import { User } from "./user-types";

export const initialUsers: User[] = [
  {
    id: 1,
    name: "Trần Văn Hiến",
    email: "hientv@fpt.edu.vn",
    role: "LECTURER",
    status: "Active",
    code: "HienTV",
    avatar: "",
  },
  {
    id: 2,
    name: "Nguyễn Văn An",
    email: "annv@fpt.edu.vn",
    role: "MEMBER",
    status: "Active",
    code: "SE160001",
    avatar: "https://github.com/shadcn.png",
  },
  {
    id: 3,
    name: "Lê Bảo Lưu",
    email: "luulb@fpt.edu.vn",
    role: "MEMBER",
    status: "Reserved",
    code: "SE160002",
    avatar: "",
  },
  {
    id: 4,
    name: "Hoàng Văn Drop",
    email: "hoangvd@fpt.edu.vn",
    role: "MEMBER",
    status: "Dropped",
    code: "SE160099",
    avatar: "",
  },
  {
    id: 5,
    name: "Phạm Thị Cô",
    email: "phamthico@fpt.edu.vn",
    role: "LECTURER",
    status: "Active",
    code: "CoPT",
    avatar: "",
  },
  {
    id: 6,
    name: "Đỗ Nam Trung",
    email: "trungdn@fpt.edu.vn",
    role: "MEMBER",
    status: "Active",
    code: "SE160003",
    avatar: "",
  },
];
